### PR TITLE
finally merging mecanum to dev

### PR DESCRIPTION
**Pull request by nh-oriki**
this is it, we're finally approaching having a MVP as needed. it's about time to merge in mecanum, a branch that has far outstepped it's single-feature-per-branch requirements. anyway, included in mecanum: 
* Travis CI (that's already been merged up, ignore that)
* Add a number of subsystems.
    - Class `BallIntake` - Spinny lad for the ball intake. Could use some additions.
        - Command class `IntakeSpin`
        - Command class `IntakeStop`
    - Class `MecanumDriveSubsystem` - A simple wrapper for wpilib's preexisting MecanumDrive class. Does the job.
        - Command class `DriveBot`
        - Command class `DriveFullStop` - completely halts all the motors on the drive
    - Class `PneumaticTester` - Likely something that's going to get replaced by a more cemented MecanumDrive Soon:tm:.
        - Command class `OpenSolenoid`
        - Command class `CloseSolenoid`
* A number of triggers for the joysticks.
    - Class `DialTrigger` - A trigger for when the dial (or slider, depending on the stick) moves.
    - Class `MainAxisTrigger` - A trigger that triggers on any X or Y movement on the joystick.
        - ~~Note: this should probably get Z-axis added, but we're not there quiiite yet.~~ Done.
    - Note: Joystick triggers come with free deadzoning.
* Some functional code to control the mecanum drive that I'll need to update in dev once we have a functional robot (to test it with the new stick, of course)
* The addition of some test code for the pneumatic solenoids on the robot. expect this to get expounded upon this week with the actual attachment and ID numberings of the solenoids becoming apparent.
* Fix the indentation on just about everything.

I think that's it. Any questions? Any review approvals?

### CODE REVIEW

**Review by rezafouladian — APPROVED** [review]
yeh

**Review by Arinerron — APPROVED** [review]
looks nice, other than the 2 width spacing

**Comment by nh-oriki** [comment]
> looks nice, other than the 2 width spacing

If you can highlight the files I'll go in and redo them to four. It's probably just the IDE trying to adapt automatically to a wpilib template that 2 width indentation by default ~~along with me being too consistently sleep deprived to care while I'm trying to get the pile of metal to chooch~~

**Comment by nh-oriki** [comment]
now featuring tab fixes. time to merge to dev, I think.

**Pull request merged**
